spring:
  application:
    name: famiplan
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/famiplan}
    username: ${SPRING_DATASOURCE_USERNAME:changeme}
    password: ${SPRING_DATASOURCE_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mvc :
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8081

app:
  admin:
    username: ${APP_ADMIN_USERNAME}
    password: ${APP_ADMIN_PASSWORD}

