spring:
  application:
    name: famiplan
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/famiplan}
    username: ${SPRING_DATASOURCE_USERNAME:yrogfamiplan}
    password: ${SPRING_DATASOURCE_PASSWORD:Yrog0807}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081

